name: Deploy

on:
    push:
        branches:
            - main
        paths:
            - 'src/gadgets/**'
            - 'src/global/**'
            - 'src/widgets/**'
            - 'src/templates/**'
    schedule:
        - cron: '17 16 * * *' # Daily 00:17 CST
    workflow_dispatch:

permissions:
    contents: read

env:
    PASSWORD: ${{ secrets.PASSWORD }}
    USERAGENT: ${{ secrets.USERAGENT }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v6
              with:
                  version: 11.8.0
            - name: Set Node Version
              uses: actions/setup-node@v7
              with:
                  node-version: 24.x
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Deploy
              run: pnpm run deploy
